### ISSUE TITLE
odd shadow appearing in modal demos

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-next#2193] opened 2019-08-26 21:15 UTC
this is present in both the modal and with wizard, it appears to be caused by the `backdrop-filter` on `.pf-c-backdrop`
<img width="623" alt="Screen Shot 2019-08-26 at 4 46 42 PM" src="https://user-images.githubusercontent.com/287880/63724095-5d8b3b00-c82d-11e9-9f5f-43a0c41e2736.png">
<img width="1281" alt="Screen Shot 2019-08-26 at 10 30 28 AM" src="https://user-images.githubusercontent.com/287880/63724096-5d8b3b00-c82d-11e9-9e17-2943bb5a5f25.png">
It only appears when hovering outside the viewport in Chrome.
[Based on the support](https://caniuse.com/#feat=css-backdrop-filter) for this I'd say we drop it until it's stable.

**Comment by mcoker** [comment] 2019-08-29 22:04
Looks like this is a known issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=983117
https://bugs.chromium.org/p/chromium/issues/detail?id=986206

A fun way to reproduce it

![Untitled](https://user-images.githubusercontent.com/35148959/63979559-ca494400-ca7e-11e9-9d3a-5f4589771134.gif)

Here's what the page looks like with and without the filter

<img width="2150" alt="Screen Shot 2019-08-29 at 4 55 29 PM" src="https://user-images.githubusercontent.com/35148959/63979604-ebaa3000-ca7e-11e9-85fa-59674038c58d.png">
<img width="2150" alt="Screen Shot 2019-08-29 at 4 55 10 PM" src="https://user-images.githubusercontent.com/35148959/63979605-ebaa3000-ca7e-11e9-83ce-d939597fa1c1.png">

I think it's safe to disable, WDYT?

**Comment by mcoker** [comment] 2019-09-06 22:32
Closing this, going to create a blog post about it.

**Closed by mcoker** 2019-09-06 22:32 UTC
Labels: bug, css
