### ISSUE TITLE
Alert h4 line-height issue

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-next#1991] opened 2019-06-26 22:09 UTC
We're seeing a Bootstrap-related alignment issue in PF4 in OpenShift:
<img width="452" alt="error" src="https://user-images.githubusercontent.com/7014965/60216092-256c7980-9837-11e9-8eef-7eb813651dec.png">

The icon isn't aligned with the text; we have to manually override it with `line-height: var(--pf-global--LineHeight--md)`. Anything you guys can do on your end?

**Comment by rachael-phillips** [comment] 2019-06-27 13:30
@christiemolloy making you aware.

**Comment by christiemolloy** [comment] 2019-07-09 14:00
@rebeccaalpert could you use the inspector and send me a screenshot, looks like the padding is off around the h4, but I want to be sure because I can't reproduce the issue in pf4 right now. Or is there a link that you can send me?

**Comment by rebeccaalpert** [comment] 2019-07-09 17:29
https://console-openshift-console.apps.taylordev.devcluster.openshift.com/k8s/ns/openshift-service-ca/pods/apiservice-cabundle-injector-85c86c779-dqbdb/environment

It has an expired certificate, so Chrome will complain at you. I'm sending you the login credentials via Slack.

You need to uncheck .co-alert h4 on .pf-c-alert__title (that's our workaround for now) to see it. It seemed related to Bootstrap's _scaffolding.scss line height for h4s since the Alert looks great when that's unchecked. Sam Padgett thought PF4 should be able to handle this without a workaround on our end.

**Comment by christiemolloy** [comment] 2019-07-09 21:07
@rebeccaalpert I checked out the openshift link, thanks for linking that to me.
The issue thats occuring is that the bootstrap scaffolding.scss file targets h1-h6 and assigns them a line-height of 1.1 which is overriding the line-height that we set in patternfly's fonts.scss file, so there is nothing we can do on patternfly's end. This is a specificity problem and until the team gets rid of the dependency on the bootstrap file, I would suggest that instead of writing the class `.co-alert h4` (because its so specific) the devs should add a line-height to the alert title like this so that it will override the line-height that is being set from the bootstrap file and work for all heading levels:

```
.pf-c-alert__title {
  line-height: var(--pf-global--LineHeight--md);
}
```

**Comment by christiemolloy** [comment] 2019-07-15 13:14
closing this issue because there is nothing to do on patternfly's end

**Closed by christiemolloy** 2019-07-15 13:14 UTC
