### ISSUE TITLE
Loading Skeleton Pattern

### ISSUE THREAD

**Issue by alecmerdler** [patternfly/patternfly-next#745] opened 2018-09-20 05:45 UTC
Are there any plans to introduce the progressive loading [_skeleton screen_ pattern](https://medium.com/ux-for-india/facilitating-better-interactions-using-skeleton-screens-a034a51120a5) into this project? It's great for reducing perceived load time for webapps that consume large amounts of backend data.

**Comment by LHinson** [comment] 2018-09-20 12:57
Hey @alecmerdler, no plans atm as we are currently building out PF4 to meet feature parity with PF3. That said, can you provide a bit more information? 

* What product/project does this impact?
* List any product/project release(s) and timelines.
* Are you interested in HTML/CSS only or leveraging a PF-React implementation? 

I'm going to go ahead and add this to our 4.x milestone so the request stays on our radar.

**Comment by alecmerdler** [comment] 2018-09-21 20:16
The `openshift/console` project (previously CoreOS Tectonic Console) would greatly benefit from this pattern. For example, once the app starts up, it must perform API discovery against the Kubernetes API (hitting >40 endpoints) before it can correctly render the current view. Obviously a backend solution would be ideal, but because we are constrained by the limitations of the Kubernetes API, a client-side solution is necessary.

I think just the CSS styles + animations are fine, framework-specific implementations are pretty easy.

**Comment by LHinson** [comment] 2018-09-24 19:04
This is great information. Do you have any specific timelines yet? @alecmerdler

**Comment by serenamarie125** [comment] 2018-09-27 20:27
@LHinson in doing this, i think we need to understand/design how filtering/sorting works with this component.  Assuming the data isn't received in a particular order.

**Comment by LHinson** [comment] 2018-09-28 14:03
@serenamarie125 will you add this as part of the inventory/requirements list that you are working on for OpenShift? That way, I think this will help us understand how this request fits into the larger picture of what's required for OpenShift and we can determine how PatternFly timelines can adjust to address these the various priorities. 

Does that work for you @alecmerdler?

**Comment by alecmerdler** [comment] 2018-09-30 23:46
That's fine, we will probably prototype an incremental loading pattern in `openshift/console` to address the performance issues. Once Patternfly has a pattern, we can consume it.

**Comment by mcarrano** [comment] 2019-05-16 18:19
There is some related design work here: https://docs.google.com/presentation/d/1kfKbl5HtumYiNm-ubJxxP93EqJjfThijEd6n1QIhD60/edit?usp=sharing

**Comment by mcarrano** [comment] 2019-12-06 21:42
This looks like a duplicate of https://github.com/patternfly/patternfly-next/issues/2007 Will close.

**Closed by mcarrano** 2019-12-06 21:42 UTC
Labels: P3, interaction design
