### ISSUE TITLE
Modal Footer Button placement

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-next#2056] opened 2019-07-16 14:02 UTC
@katierik just filed this issue in org: https://github.com/patternfly/patternfly-org/issues/1290 to adjust the button placement in the modal.

This isn't a bug as the buttons exist on the right in Core, however I do remember discussion about the button placement. @mcarrano and @mcoker what do you think about moving the buttons to the left I don't think it will be a breaking change..?

**Comment by mcoker** [comment] 2019-07-16 14:09
@christiemolloy we have this issue to move the buttons - https://github.com/patternfly/patternfly-next/issues/1599

The problem with aligning the actions to the left is that the buttons would be out of order with the primary button as the last button in the list. We could try and fix that by using `flex-direction` to reverse the order visually, but that would give us a11y issues and may or may not cause other problems, depending on what someone has put in the modal footer (i.e., something other than buttons).

Can you think of a way to do it without creating a breaking change?

**Comment by tqle** [comment] 2019-07-16 15:46
Hi, been looking at your code set and have a suggested fix. There are several ways to fix this.
`
// Solution 1. Use align-self: flex-start (left) or flex-end (right)
// or just apply another style on your footer to control the align-self to change the flex start or end direction. 
// Adding another style to the footer maybe the clean way of doing it. If you ever decide to do RTL you can control this behavior and change this dynamically.
// to allow more flexibility but not making this specific to the footer.
.pf-c-modal-box__footer {
    display: flex;
    flex: 0 0 auto;
    align-items: center;
    margin-top: var(--pf-c-modal-box__footer--MarginTop);
    text-align: left; /** Allows static text or content to be left align **/
    align-self: flex-start; /** Makes all the flex items align to flex start or left **/
}

//Solution 2: Use display: inline-block. Text align will move buttons or any element to left. To make it to the right use text-align: right
// Same as above you can pass another css class to override the display flex to be display block.
.pf-c-modal-box__footer {
    display: inline-block; /** override or change to be inline-block if you don't want to use flex-box **/
    margin-top: var(--pf-c-modal-box__footer--MarginTop);
    text-align: left; /** All items will be moved to the left **/
}

//Open code to the expand code to code pen. Add the following buttons and css changes to your //example modal or dev environment.
//Add the following css to the web inspector above or add another class to your footer change the display block direction. 
 <footer class="pf-c-modal-box__footer">
<button class="pf-c-button pf-m-primary" type="button">
  Primary
</button>
<button class="pf-c-button pf-m-secondary" type="button">
  Secondary
</button>
 </footer>

// Or add some class to change the align-self, ex. align-self-flex-start
 <footer class="pf-c-modal-box__footer align-self-flex-start">
 <button class="pf-c-button pf-m-primary" type="button">
  Primary
</button>
<button class="pf-c-button pf-m-secondary" type="button">
  Secondary
</button>
 </footer>

`

**Comment by mcoker** [comment] 2019-07-17 20:42
Hey @tqle, thanks for the contribution! These are all valid approaches, and I appreciate the feedback. 

The problem with adjusting the alignment currently has to do with introducing a breaking change into a PatternFly user's UI, meaning we want to avoid changing an existing feature that would cause a user's UI to break in some way without a corresponding change in the user's application CSS, markup, etc. Aligning the footer or it's contents to the left would leave actions and potentially other content in the footer out of order since in a left-aligned footer, the actions should be ordered (primary to secondary) from left to right, and in a right-aligned footer, ordered right to left. We could try to visually rearrange the footer contents using `flex-direction` or `order`, but since we don't know what elements could exist in a user's modal footer, rearranging the contents could be a breaking change, too.

We have a breaking change release scheduled in the near future where we will be able introduce CSS changes into PatternFly that will need to be accompanied with markup changes in order for the components to display as intended. That work will be completed in https://github.com/patternfly/patternfly-next/issues/1599 if you would like to subscribe or be involved in any way.

**Comment by tqle** [comment] 2019-07-19 00:47
@mccoker - Ok. I understand the issue.  The breaking change sounds like the best solution.  I guess my only question is if there is a limit on how many elements that go in the footer or what the ux guidelines for the footer content.  I'll be glad to help in any way.

**Comment by mcoker** [comment] 2019-07-19 14:48
@tqle I think this would be a great question to post on our forum where designers can answer questions about best practices, and it will serve as a resource for other users who may have this question in the future. https://forum.patternfly.org

**Comment by christiemolloy** [comment] 2019-07-19 18:48
Closing this issue in favor of #1599

**Comment by LHinson** [comment] 2019-07-29 20:50
As Christie stated, closing in favor of 1599

**Closed** 2019-07-29 20:50 UTC
Labels: P3, breaking change, help wanted, update symbol library
