### ISSUE TITLE
Add styling for validated text input

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-next#2320] opened 2019-10-01 14:27 UTC
Would like to have common styling for text inputs that need to indicate the value has been validated.

Similar to:

![image](https://user-images.githubusercontent.com/11633780/65971316-fff29b80-e435-11e9-9cb4-8a509e314303.png)

**Comment by mcoker** [comment] 2019-10-01 15:08
cc @mcarrano @kybaker

**Comment by jeff-phillips-18** [comment] 2019-10-01 16:43
@mcarrano @kybaker I have the code ready to implement this if this is agreed upon. The only issue I have is getting the right color green to pass a11y tests and still show the bottom border of the text input as green. I could use some help there.

**Comment by mcarrano** [comment] 2019-10-01 20:58
@jeff-phillips-18 While I don't really see a problem with what you've done here, I do have a question about intended usage. Typically on a form you only reflect feedback from validation if there is an error. Is the suggestion to give feedback on all fields, even those with no errors? Only certain fields? Would like to hear more about the use case.

**Comment by jeff-phillips-18** [comment] 2019-10-01 21:08
In a form the user can enter a value. At that time, we need to determine if the value is valid before allowing the user to continue. The validation process can take some time and we want to give the user some feedback that the field has in fact been validated once the validation completes.

The help text is updated during the validation process to inform the user that the validation is in progress.

**Comment by jeff-phillips-18** [comment] 2019-10-01 21:23
Use case is to provide feedback for a text input that takes some time to validate once the user enters the text. During the validation the help text is updated to inform the user that the validation is in process. Once complete we want to provide feedback that the validation was successful.

@parvathyvr @serenamarie125 @mceledonia @rachael-phillips

**Comment by mcarrano** [comment] 2019-10-02 15:02
@jeff-phillips-18 Thanks for the explanation. This makes sense. @kybaker @mceledonia do you have input on the colors to use? Seems we'd want to use the same color treatment as a 'success' inline alert.

**Comment by kybaker** [comment] 2019-10-02 15:10
@mcarrano Agreed - using the success treatment makes sense to me.

**Comment by jeff-phillips-18** [comment] 2019-10-02 18:13
Using the success inline treatments yields:
![image](https://user-images.githubusercontent.com/11633780/66070055-913d3d00-e51e-11e9-8100-751272ebb025.png)

It gets the point across, but the text color setting doesn't stand out to me. Is this what we want?

@mcarrano @kybaker

**Comment by serenamarie125** [comment] 2019-10-02 18:28
so we had reached out to @mceledonia and the suggestion was to use --pf-chart-color-green-400 for the icon & the underline, but open for discussion for sure!

**Comment by mceledonia** [comment] 2019-10-02 18:30
Yeah the lime green feels too bright to me here since it's not over a dark green background like the alerts. It's subjective but it kinda feels a little fluorescent, and I thought the regular green fixed that.

@kybaker This all gets back to that secondary color palette from brand, it would be nice to only have one set of greens so we can avoid the confusion.

**Comment by jeff-phillips-18** [comment] 2019-10-03 11:17
Here are both together for comparison:

![image](https://user-images.githubusercontent.com/11633780/66120262-79aa9680-e5a8-11e9-9fbd-84253808ff91.png)

**Comment by serenamarie125** [comment] 2019-10-03 12:51
There are issues with success-100 #2168 this is why we would like to change it to the darker green.

**Comment by mcarrano** [comment] 2019-10-03 13:58
@kybaker @mceledonia if you have no objections, I would like to go ahead with using a darker green to indicate success across the board. Looks like this at least affects, progress bars, alerts, and this new validation pattern. Can we change this globally (via a CSS variable) or will we need to update each component?  @mcoker thoughts?

**Comment by jeff-phillips-18** [comment] 2019-10-04 17:30
@mcoker Should I update the global color with my fix for this issue or is that going to be done separately?

**Comment by serenamarie125** [comment] 2019-10-04 19:46
@kybaker what are your thoughts here?  We need this for 4.3 so the earlier the better!  Thanks

**Comment by mcoker** [comment] 2019-10-04 19:54
@mcarrano that sounds fine to me. Confirmed we're only using that color in those 2 components:

```
src/patternfly//components/Progress/progress.scss:  --pf-c-progress--m-success__bar--BackgroundColor: var(--pf-global--success-color--100);
src/patternfly//components/Progress/progress.scss:  --pf-c-progress--m-success__status-icon--Color: var(--pf-global--success-color--100);
src/patternfly//components/Alert/alert.scss:  --pf-c-alert--m-success__icon--BackgroundColor: var(--pf-global--success-color--100);
src/patternfly//components/Alert/alert.scss:  --pf-c-alert--m-inline--m-success__icon--Color: var(--pf-global--success-color--100);
src/patternfly//components/Alert/alert.scss:  --pf-c-alert--m-inline--m-success--before--BackgroundColor: var(--pf-global--success-color--100);
```

The only concern I have is that if someone is using `$pf-color-light-green-400` or `#92d400` directly as the value for a custom style in their application in a way that is intended to match our use of `$pf-global--success-color--100` in our components, but I would consider that an improper way to use the color, so I don't think it would be a breaking change - just something to keep in mind.

**Comment by kybaker** [comment] 2019-10-04 20:07
@serenamarie125 I agree with both Michaels here. I am fine with the darker color design change as long as it is not breaking.

**Comment by mceledonia** [comment] 2019-10-04 20:36
Jotting down some notes here:

[current success variables]
success-100 = light-green-400 = #92d400, on white = 1.8 (fail)
success-200 = light-green-600 = #486b00, on white = 6.22 (pass)

[success alert styling]
success-200 on top of success-100 = 3.45 (AA+/fail)

Two options I see here:

1.
[changing from light-green to -green]
green-400 on top of white = 3.10 (AA+ = fail)
green-500 on top of white = 4.85 = (AA = pass)

So changing success-100 to green-500 works well on white, but not well for the toast alert styling. Since it's -500, that means we need to go up a step to -700 for the icon fill (success-200) which is very dark and still doesn't get us to AA (3.3)
<img width="221" alt="image" src="https://user-images.githubusercontent.com/30935938/66237113-46f4c100-e6c2-11e9-8332-b5886aa50454.png">
FAIL

1b.
The other option is to use -500 as our dark color (success-200) and go lighter for success-100..
that gets us to 3.46, still not AA (AA+) and also starts to not fit in very well with the other alerts
<img width="244" alt="image" src="https://user-images.githubusercontent.com/30935938/66237162-67bd1680-e6c2-11e9-9987-93f1c6c03a30.png">
FAIL

 2. [Darker light-green]
Light-green-500 on white = 3.14 = fail
Light-green-600 on white = 6.22 = pass, but ugly color. 
FAIL

2b. [Both?]
We already know green-500 on white = pass
Does Light-green-100 pass with green-500 on top? No, but it is closer with 4.17. On to 2c.
FAIL

2c. [Using opacity to lighten light-green-100 so green-500 passes on it.]
I think this is our best option for the short term, going for no breaking changes. Essentially forcing that 4.17 up to a 4.5. After all this we might want to rethink the toast designs in the future, as getting the contrast ratio is proving difficult.
Light-green-100 (#E4F5BC) @ 49% opacity behind green-500 (#467F40) finally gets us to 4.5. 
<img width="234" alt="image" src="https://user-images.githubusercontent.com/30935938/66237974-6ee52400-e6c4-11e9-9f81-87e8fcc9b376.png">
PASS

### Conclusion/proposal

Success-100 = light-green-100 set to 49% opacity
Success-200 = green-500 = #467F40 

Success-100 on Success-200 = 4.5 (PASS)
Success-200 on white = 4.85 (PASS)

Side note - these troubles _might_ be solved by the new secondary palette the brand team is implementing.

**Comment by jeff-phillips-18** [comment] 2019-10-07 11:06
Using
Success-100: $pf-color-light-green-100
Success-200: $pf-color-green-500

I get:

![image](https://user-images.githubusercontent.com/11633780/66306605-11bdbe00-e8d0-11e9-918b-20abd5c2d193.png)

Which looks reasonable to me and doesn't need to introduce opacity which I would think would be much more of a breaking change. Maybe this doesn't get us all the way there but it's pretty close and an improvement on what we have currently.

**Comment by mceledonia** [comment] 2019-10-07 12:53
@jeff-phillips-18 Agreed, and this definitely works for now but I do think we should mark it as something we still need to solve. Shooting for the numbers here on accessibility we unfortunately come up short without the opacity.

@kybaker I'm hoping the new brand secondary colors come in handy here, if not we can always reconfigure the toast design to avoid the color on color.

cc @mcoker @jgiardino @mcarrano

**Comment by mcoker** [comment] 2019-10-09 16:13
Went over the proposal from @mceledonia and while this wouldn't technically be a breaking change for any patternfly components, it likely would be a visual breaking for applications using our `pf-global--success-color` variables to style success states in their application, depending on how they're using the success color vars. In order to proceed with this proposal, I'd prefer wait to introduce this in a breaking change release.

@mceledonia is going to re-evaluate the existing green color palette and see if there is a way we can tweak the existing variables such that they provide the proper contrast and wouldn't result in breaking changes for users using the existing success color vars to represent state in their application.

**Comment by mceledonia** [comment] 2019-10-09 16:41
So far I have tried our chart colors, the new brand colors, a modified version of our chart colors which introduces a darker -600, and now I'm trying out a modified brand new green based on our current colors and the new brand direction. No luck yet, I can make it work with a whole new green palette, but this begs the question:

**Should we be changing our entire green palette for this, or should we reconsider the toast alert design?** 

This problem stems from a very specific set of requirements we are currently imposing on our green palette. It must -
- Have a "main" green color which is dark enough to be accessible over white for general usage (think success icons, success progress bar state). This isn't difficult, but it must also...
- Not be too dark, to ensure a darker -600 or -700 will work over it without just basically being black. <- This is where we get in trouble and is forcing us to create a new green palette.

Here's a few tests I've run, I'm still working on this and I'm confident I'll be able to find a solution, but the solution is a brand new set of greens which won't necessarily fit the cadence of the other palettes. So I guess I'm asking if that's worth it just to meet that second criteria I listed above.

I would be in favor of changing the toast design altogether to something that has more contrast, but I know that in itself is probably a breaking change.

@mcoker @kybaker @mcarrano 

![image](https://user-images.githubusercontent.com/30935938/66501845-2c3f9500-ea92-11e9-9432-f805e4d48f85.png)

**Comment by mceledonia** [comment] 2019-10-09 18:46
Spoke with @kybaker and we landed on a solution- 

Success-100 -> Chart-green-400 (4CB140)
Success-200 -> New green-600 (183C14)

These two colors pass when stacked. Success-100 does not pass on top of white, which in general is fine as long as there is an accessible indicator of the success otherwise, such as supportive text under the input as seen above. Another option here is adding an accessible success-150, for areas where we do need the accessibility on white. That color could be:

success-150 = 3E8635 which gives us a perfect 4.5 contrast ratio. 
We can then reconfigure things like the progress bar or the success input underline to use this color which does pass, without having to worry about a darker color which also passes when on top.

@mcoker @kybaker @jgiardino

**Comment by mceledonia** [comment] 2019-10-09 19:55
We're in business, folks! @jeff-phillips-18 @mcoker @mcarrano @kybaker @jgiardino 
And from what I can tell, no breaking changes. 

1. Change Green-500 to #3E8635 (for perfect 4.5 over white)
2. Change Success-100 to call Green-500
3. Change Scccess-200 to call Green-700 (current) 

![image](https://user-images.githubusercontent.com/30935938/66515429-20150100-eaad-11e9-8b2b-8bc44d746ce8.png)

**Comment by jgiardino** [comment] 2019-10-09 19:59
I commented on the 24px qualifying as large text in [another issue](https://github.com/patternfly/patternfly-next/issues/1474#issuecomment-540162775), if you're interested in how we arrived at that conclusion.

**Closed** 2019-10-23 14:06 UTC
Labels: enhancement
