### ISSUE TITLE
Update needed to icon sizes

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-next#1933] opened 2019-06-14 20:38 UTC
The current icon sizes are:
$pf-global--icon--FontSize--sm: pf-font-prem(10px) !default;
$pf-global--icon--FontSize--md: pf-font-prem(18px) !default;
$pf-global--icon--FontSize--lg: pf-font-prem(24px) !default;
$pf-global--icon--FontSize--xl: pf-font-prem(54px) !default;
source https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss

The are some components that use icon sizes between sm & md, such as the date picker (16px and 14px), chip (12px), popover (11px), etc. 

We need to either
~a) determine a new sm size (and rename 10px to xs)~
~b) reduce md to 16px~
c) keep existing sm and md sizes and update components to comply

Thank you!

@mceledonia @kybaker @mcarrano @LHinson @rachael-phillips @gdoyle1 

Decisions:

- [x] textbox icons --> 18px
- [x] chips --> 10px, times (no circle)
- [x] popovers --> 18px
- [x] breadcrumbs --> 10px
- [x] modal --> 18px
- [x] masthead --> 18px
- [x] filters --> 18px
- [x] progress bar status icons --> 18px

**Comment by rachael-phillips** [comment] 2019-06-19 19:34
Thanks for filing! @mceledonia is working on icon sizes right now I believe. Michael, are there any relevant issues already open for this effort?

**Comment by ajacobs21e** [comment] 2019-06-20 18:31
<img width="308" alt="Screen Shot 2019-06-14 at 2 02 26 PM" src="https://user-images.githubusercontent.com/6415742/59872517-f2724380-9367-11e9-992b-693f5a3fcb37.png">
I think the 18 is a bit big but 10 is too small. This would apply to other icons in a text field like search magnifying glass and the time clock.
@mceledonia  @kybaker

**Comment by mceledonia** [comment] 2019-06-20 18:31
@rachael-phillips This relates directly to what I was working on, our next steps are to adjust any icon sizes that don't match our variables in the sketch library and we will be all set! Sticking with icon font for now rather than worrying about transferring to SVG, as icon font works just fine and the switch would not be worth the time right now.

**Comment by mceledonia** [comment] 2019-06-20 18:33
@ajacobs21e Let's go with 18 for now since we want to try not introducing a fifth variable, and 10 just looks funny 😁

**Comment by ajacobs21e** [comment] 2019-06-20 18:36
![Screen Shot 2019-06-20 at 2 35 00 PM](https://user-images.githubusercontent.com/6415742/59872885-bee3e900-9368-11e9-8cfe-1ac3c44b2082.png)
Chip
@mceledonia @kybaker

**Comment by ajacobs21e** [comment] 2019-06-20 18:40
![Screen Shot 2019-06-20 at 2 39 55 PM](https://user-images.githubusercontent.com/6415742/59873112-4df10100-9369-11e9-9001-dda3165d77eb.png)
Popovers

**Comment by ajacobs21e** [comment] 2019-06-20 18:44
![Screen Shot 2019-06-20 at 2 43 55 PM](https://user-images.githubusercontent.com/6415742/59873364-d96a9200-9369-11e9-99bd-c2a7f927713a.png)
Breadcrumbs
@mceledonia

**Comment by lboehling** [comment] 2019-06-20 18:52
Modal is already built with an 11px close icon on https://pf4.patternfly.org/components/ModalBox/examples/.   

attaching examples with it at 10px and 18px. @mceledonia 
<img width="564" alt="Screen Shot 2019-06-20 at 2 50 43 PM" src="https://user-images.githubusercontent.com/46571616/59873875-f2c00e00-936a-11e9-9d12-4d698de23cc3.png">

**Comment by ajacobs21e** [comment] 2019-06-20 18:54
Masthead icons are 16px... pics from Gina coming soon

**Comment by mceledonia** [comment] 2019-06-20 18:57
@ajacobs21e  [CHIP]

This is awesome
For the chip - this is actually the same problem the Red Hat logo had from being contained inside a circle. My proposal is we switch the icon to the plain X (no circle) and at 10px it should look the proper size.

**Comment by mceledonia** [comment] 2019-06-20 18:58
@lboehling [MODAL]

I say 18, it feels a little big but it is definitely better than 10

**Comment by mceledonia** [comment] 2019-06-20 18:58
@ajacobs21e [BREADCRUMBS] 

10 for sure!

**Comment by mceledonia** [comment] 2019-06-20 18:59
@ajacobs21e [POPOVERS]

This one is tough and I think half the problem is the misalignment with the text. I think 18 will feel better if we can get it to be realigned with the text... Do we know why it is misaligned?

**Comment by ajacobs21e** [comment] 2019-06-20 19:00
Chip with 10px naked X
![Screen Shot 2019-06-20 at 2 59 42 PM](https://user-images.githubusercontent.com/6415742/59874387-1899e280-936c-11e9-9211-01598901b6d5.png)

**Comment by mceledonia** [comment] 2019-06-20 19:01
It is also a little difficult to get a sense of scale since we aren't seeing these in context. I think we can make general decisions but definitely see how they feel in the larger context of a screen @ajacobs21e @gdoyle1 @lboehling

**Comment by ajacobs21e** [comment] 2019-06-20 19:05
@mceledonia yeah I zoomed out before taking the screenshot because I though the same thing but it does look much better at 100% zoom instead of 600%.

I also looked at the popover and it has spacers overlapping so I'll chat with you offline about that. But yes I agree that 18px works better there too (and then matches the modal)

**Comment by gdoyle1** [comment] 2019-06-20 19:07
@mceledonia Masthead icons 
![Screen Shot 2019-06-20 at 3 06 44 PM](https://user-images.githubusercontent.com/30870144/59874791-2439d900-936d-11e9-94e2-97fe1f2c54a9.png)

**Comment by mceledonia** [comment] 2019-06-20 19:22
@gdoyle1 [MASTHEAD]

Let's go 18 there!

**Comment by gdoyle1** [comment] 2019-06-20 20:01
Updated all icon sizes in current designs and deleted the old random px sized icons out of icons list. I think this should solve everything! Probably can close this out

**Comment by mceledonia** [comment] 2019-06-20 20:19
@gdoyle1 @ajacobs21e @lboehling awesome work! thanks for taking this on and crushing it.

**Comment by ajacobs21e** [comment] 2019-06-20 20:35
@mceledonia thanks for answering our 400 questions!

**Comment by lboehling** [comment] 2019-06-24 18:34
@mceledonia @ajacobs21e found another inconsistency while working on progress bars: icons are 16px on https://pf4.patternfly.org/components/Progress/examples/. Updating to 18px in sketch library. 
![Screen Shot 2019-06-24 at 2 32 22 PM](https://user-images.githubusercontent.com/46571616/60043045-2661a780-968d-11e9-9678-37a0a43a48a6.png)

**Comment by mmenestr** [comment] 2019-06-26 13:03
@mceledonia Carets for dropdowns are 16px, but i've been doing them with 10px - thoughts?

Web Example:
<img width="422" alt="Screen Shot 2019-06-26 at 8 59 22 AM" src="https://user-images.githubusercontent.com/51165119/60181857-211d6d80-97f1-11e9-9116-6ae68c2e49ee.png">

Mine:
<img width="271" alt="Screen Shot 2019-06-26 at 9 03 17 AM" src="https://user-images.githubusercontent.com/51165119/60181905-414d2c80-97f1-11e9-95f4-526608c2ed28.png">

**Comment by mmenestr** [comment] 2019-06-26 13:17
@mceledonia overflow arrows - seems similar to breadcrumbs situation, they are around 16px on inspect, but i've made them 10px - thoughts?

Example:
<img width="761" alt="Screen Shot 2019-06-26 at 9 07 51 AM" src="https://user-images.githubusercontent.com/51165119/60182893-2e3b5c00-97f3-11e9-9408-16baa0a624c2.png">

Mine:
<img width="342" alt="Screen Shot 2019-06-26 at 9 16 39 AM" src="https://user-images.githubusercontent.com/51165119/60182869-22e83080-97f3-11e9-98ec-9782dfcd7585.png">

**Comment by mceledonia** [comment] 2019-06-26 13:33
@mmenestr I think your screenshot looks good! Are you measuring with the icon font size or the true icon size? When I change the icon font to 10px it gets super tiny, a lot smaller than what you have there. I think what you have looks good though.

**Comment by mmenestr** [comment] 2019-06-26 14:04
@mceledonia not sure if you're referring to inspect or on sketch. But for inspect the font size was 16px, but the icon measurements were 8x16px (which is what I was looking at). On sketch, I just chose the icons / small / angle-left and angle-right version of the icon, so 10px sizing and that's what it looks like!

**Comment by mcarrano** [comment] 2019-12-09 21:32
@mceledonia @gdoyle1 @mmenestr Is there still an issue here? Can this one be closed out?

**Comment by gdoyle1** [comment] 2019-12-10 12:57
@mcarrano This was mostly solved in the design kit but will also be solved through the larger icon effort so I think we can close this.

**Closed** 2019-12-10 13:39 UTC
Labels: enhancement
