### ISSUE TITLE
Visuals: Secondary text color on gray problem

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-next#1864] opened 2019-05-29 14:37 UTC
## The problem

Our secondary text color does not meet contrast requirements when placed on top of our light gray background color `#EDEDED`. This has prevented use of the color in a design solution, therefore we should find a solution if we want to have a usable secondary text style.

The options I see are (in no particular order):
1. Use our theming system to darken our secondary text color when placed over a gray background
2. Introduce another color variable between 600/700 which meets minimum contrast requirement when placed over gray background (`$pf-color-black-650`)
3. Reconsider how we use content over gray background
4. Reconsider secondary text style, perhaps instead of color we change size/weight

## Current styling information

Our current secondary text style is:
`$pf-global--Color--200`
which is 
`$pf-color-black-600`
which is
`#72767b`

---

Currently our secondary text color on gray gives us a contrast ratio of
### 3.91 AA+ 
4.5 is required

---

Bringing our secondary text color variable up one step to ` $pf-color-black-700` `#4d5258` puts us way over the requirement but lessens contrast between primary/secondary text color at
### 6.73 AA

---

## Thoughts

I'm not very partial to any of the solutions but if I had to pick one to explore it would be the 4th option I listed. I wanted to get the conversation started and throw some thoughts out there. This isn't necessarily an urgent update but I do think it's an important one as our secondary text style currently isn't usable because of this issue.

FYI
@kybaker @rachael-phillips @LHinson @maryshak1996 @mcoker @mcarrano

**Comment by mcarrano** [comment] 2019-12-09 20:23
Looks like a duplicate of #2424. Will close.

**Closed by mcarrano** 2019-12-09 20:23 UTC
Labels: visuals
