### ISSUE TITLE
Table checkbox alignment

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-next#1577] opened 2019-03-14 19:38 UTC
There is a top margin on the content element in a check table cell that seems to be only for mobile. It should likely be removed from desktop, and re-evaluated on mobile, too. Some of the table examples have proper alignment and others don't.

#### the margin
<img width="644" alt="Screen Shot 2019-03-14 at 2 36 00 PM" src="https://user-images.githubusercontent.com/35148959/54386328-b2177100-4666-11e9-8de4-608f4d5aaf21.png">

#### proper alignment
<img width="476" alt="Screen Shot 2019-03-14 at 2 38 03 PM" src="https://user-images.githubusercontent.com/35148959/54386374-c9eef500-4666-11e9-870c-3af8b35ce6f2.png">

#### improper alignment
<img width="513" alt="Screen Shot 2019-03-14 at 2 36 57 PM" src="https://user-images.githubusercontent.com/35148959/54386379-ceb3a900-4666-11e9-94a5-a02615c0077c.png">

**Comment by tqle** [comment] 2019-08-02 03:03
@mcoker - Hi. I would like to contribute a fix for this but I don't know what your PR guidelines are - do I create a branch or branch from fork.  I didn't see anything in read me or git hub on your process.

I can give you the css you need to fix below also.

The issue is your kebab button height and line heights don't match with the checkbox so they are off. If you add test outlines on them you an see they have different heights. 
Adding align-self in the table-grid.scss on the kebab (pf-c-table__action) and checkbox (pf-c-table__check) makes the centered in all responsive views.  I've tested this locally on my machine in Safari, Chrome, and FF and it works.  It also works in the other tables that have the checkbox.
Let me know if this helps :)

1.  You can get rid of this block of css in your table.scss. This is not needed or comment it out.
// .pf-c-table__check {
//   vertical-align: top;

//   > * {
//     margin-top: var(--pf-c-table__check--input--MarginTop);
//     vertical-align: top;
//   }
// }

2. Update the following in the table-grid.scss. I've added a test outline to show you it's truly center.
There's a slight optical illusion with the checkbox and the kebab that makes it not center but this will show you it's centered. 
 .pf-c-table__check {
    align-self: center; // Add ths. Align the checkbox to be center in the grid cell. 
    // margin-top: var(--pf-c-table__check--responsive--MarginTop); // comment this out or remove.
    margin-left: var(--pf-c-table__check--responsive--MarginLeft);
    .... 
    outline:1px solid blue; // <-- test to show it is truly center.

3. in same table-grid.scss - add this with existing css.
  // Action cell
  .pf-c-table__action {
    align-self: center; // <-- Add this. Align the table action button to be center in the grid
    ....

**Comment by mcoker** [comment] 2019-08-07 16:04
@tqle thanks! We would love a contribution. Just fork the repo and follow the [development instructions](https://github.com/patternfly/patternfly-next#development) to get a local build up and running, then create a branch with your fix (your commit message should follow the [semantic release format](https://github.com/semantic-release/semantic-release#commit-message-format)), push the branch to your fork, and create a pull request in this repo for it. Let me know if you need help or have any questions.

**Closed** 2019-12-12 23:12 UTC
Labels: bug, css, help wanted, p4
